name: Mac CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build dependencies
      # Building tcl to make sure we get tclInt.h
      run: |
        mkdir -p /usr/local/src/git
        cd /usr/local/src/git
        git clone https://github.com/tcltk/tcl.git
        cd tcl
        git checkout core-8-6-branch
        cd unix
        ./configure
        make
        sudo make install
    - name: configure
      run: |
        autoreconf -vi
        ./configure --with-tcl=/usr/local/lib --prefix=/usr/local
    - name: make
      run: |
        make
        make test
    - name: install
      run: sudo make install

